project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: GeneralMap.qmd
        text: General Map
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

